/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "Smoking.h"

bool_t
xdr_type(XDR *xdrs, type *objp)
{

	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_data(XDR *xdrs, data *objp)
{

	if (!xdr_type(xdrs, &objp->type))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->amount))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->smoker))
		return (FALSE);
	return (TRUE);
}
