/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SMOKING_H_RPCGEN
#define _SMOKING_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


enum type {
	TOBACCO = 0,
	PAPER = 1,
	MATCHES = 2,
};
typedef enum type type;
#ifdef __cplusplus
extern "C" bool_t xdr_type(XDR *, type*);
#elif __STDC__
extern  bool_t xdr_type(XDR *, type*);
#else /* Old Style C */
bool_t xdr_type();
#endif /* Old Style C */


struct data {
	type type;
	int amount;
	int smoker;
};
typedef struct data data;
#ifdef __cplusplus
extern "C" bool_t xdr_data(XDR *, data*);
#elif __STDC__
extern  bool_t xdr_data(XDR *, data*);
#else /* Old Style C */
bool_t xdr_data();
#endif /* Old Style C */


#define SMOKE ((rpc_uint)0x20A0FACE)
#define SMOKERS ((rpc_uint)1)

#ifdef __cplusplus
#define GET_ME_MY_SUPPLY ((rpc_uint)1)
extern "C" int * get_me_my_supply_1(data *, CLIENT *);
extern "C" int * get_me_my_supply_1_svc(data *, struct svc_req *);

#elif __STDC__
#define GET_ME_MY_SUPPLY ((rpc_uint)1)
extern  int * get_me_my_supply_1(data *, CLIENT *);
extern  int * get_me_my_supply_1_svc(data *, struct svc_req *);

#else /* Old Style C */
#define GET_ME_MY_SUPPLY ((rpc_uint)1)
extern  int * get_me_my_supply_1();
extern  int * get_me_my_supply_1_svc();
#endif /* Old Style C */

#endif /* !_SMOKING_H_RPCGEN */
